name: Deploy to OVH

on:
  push:
    branches:
      - main  # Déclenchement sur la branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.1
      with:
        server: ftp.votredomaine.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /www
